name: Lint
on:
  push:
    branches: [ dev ]
  pull_request:
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      run: yarn
    - name: Lint project
      run: yarn lint